[build-system]
requires = [
    "setuptools>=65.0",
    "wheel",
    "numpy>=1.20",
]
build-backend = "setuptools.build_meta"

[project]
name = "pyhelp-fortran-binaries"
version = "1.0.0"
description = "Pre-compiled HELP3O Fortran binaries"
readme = "README.md"
requires-python = ">=3.11"